import { DISCORD_INVITE } from "@/lib/links";
import { ORDER_WHATSAPP } from "@/components/templates/landing/_data/landing";

/* ============================================================
   Kebijakan Privasi — isi mengikuti cara kerja sistem yang sebenarnya (lihat docs/API.md).
   PENTING: ubah LEGAL di bawah dengan data badan usaha/pemilik yang sebenarnya, dan pastikan angka
   retensi di tabel sesuai praktik Anda. Ini bukan nasihat hukum — minta advokat meninjau sebelum dipakai resmi.
   ============================================================ */

export const LEGAL = {
  /** nama yang bertanggung jawab atas data (pengendali data) */
  controller: "ArrStudio",
  /** alamat email privasi — kosongkan bila belum ada; kontak lain tetap tampil */
  email: "",
  updated: "2026-10-04",
};

export const CONTACT = {
  discord: DISCORD_INVITE,
  whatsapp: `https://wa.me/${ORDER_WHATSAPP}`,
};

export type Block =
  | { p: string }
  | { ul: string[] }
  | { table: { head: string[]; rows: string[][] } }
  | { note: string };

export interface Section {
  id: string;
  title: string;
  blocks: Block[];
}

export interface Policy {
  title: string;
  subtitle: string;
  updatedLabel: string;
  tocLabel: string;
  backLabel: string;
  contactLabels: { discord: string; whatsapp: string; email: string };
  sections: Section[];
}

const en: Policy = {
  title: "Privacy Policy",
  subtitle: "What we collect, why we collect it, who sees it, and the choices you have — in plain language.",
  updatedLabel: "Last updated",
  tocLabel: "On this page",
  backLabel: "Back to site",
  contactLabels: { discord: "Discord (support ticket)", whatsapp: "WhatsApp", email: "Email" },
  sections: [
    {
      id: "summary",
      title: "1. The short version",
      blocks: [
        { p: "ArrStudio sells licensed Roblox kits. To run that service we need an account, a way to take payment, and a way to check that a license key is used on the places it was bought for. This policy explains the personal data involved." },
        {
          ul: [
            "We collect the minimum needed: your account details, your orders and licenses, and the technical data needed to keep the service secure.",
            "We do not sell your personal data, and we do not share it for advertising. There are no ad or tracking cookies on this site.",
            "Payments are handled by Midtrans. We never see or store your card number or e-wallet credentials.",
            "You can ask us to access, correct or delete your data at any time (section 9).",
          ],
        },
      ],
    },
    {
      id: "who",
      title: "2. Who we are and what this policy covers",
      blocks: [
        { p: `${LEGAL.controller} (“ArrStudio”, “we”, “us”) is the controller of the personal data described here. This policy covers the website, the customer dashboard, the admin tools we use to run the service, the license-check API called by our Roblox kits, and our purchase and support channels.` },
        { p: "It does not cover third-party services that we link to or that you use alongside ours (Roblox, Discord, WhatsApp, your bank). Those have their own policies, and you should read them." },
      ],
    },
    {
      id: "collect",
      title: "3. The data we collect",
      blocks: [
        { p: "We collect data in three ways: what you give us, what is created when you use the service, and what comes from services you connect." },
        {
          table: {
            head: ["Category", "What it includes", "Source"],
            rows: [
              ["Account", "Email address, display name, optional Roblox username, a unique account ID, sign-up method, and a password (stored only as a salted hash by Firebase Authentication — we cannot read it).", "You"],
              ["Discord login", "If you sign in with Discord: Discord user ID, username, avatar URL and, when verified, your email address.", "Discord, with your permission"],
              ["Orders & payments", "What you bought, price, discount code used, payment method type (e.g. QRIS, bank transfer), status and timestamps. For installment plans: total, amounts paid, dates and notes recorded by our team after checking a transfer proof.", "You / Midtrans / our team"],
              ["Transfer proofs", "If you send a proof of transfer through Discord or WhatsApp: the image or message you send, which may show your name and account details.", "You"],
              ["Licenses", "License keys, the kit, the Roblox place IDs the key is bound to, number of place slots, issue date and status.", "Generated by us / you"],
              ["License checks", "Each time a game server starts, our kit calls the license API. We receive the key, kit ID, kit version, the Roblox place ID and server job ID, and your server's IP address. We keep only the latest check time, version and a running count — not a full history.", "Your Roblox game servers"],
              ["Technical & security", "IP address, browser and device type, pages requested, timestamps and error logs; rate-limit counters (stored under a hashed key); content-security-policy violation reports.", "Automatically"],
              ["Admin activity", "For our own staff accounts: a log of administrative actions (who did what and when).", "Automatically"],
              ["Communications", "Messages you send us on Discord or WhatsApp, and your Discord / WhatsApp identifiers.", "You"],
            ],
          },
        },
        { p: "We do not intentionally collect sensitive personal data (such as health, biometric or political data), and we do not ask for government ID." },
        { note: "Roblox thumbnails and place names shown in your dashboard are fetched from Roblox’s public APIs using the place IDs you registered. We do not receive any other data about your Roblox account." },
      ],
    },
    {
      id: "use",
      title: "4. Why we use your data (and our legal basis)",
      blocks: [
        {
          table: {
            head: ["Purpose", "Data used", "Legal basis"],
            rows: [
              ["Create and secure your account, sign you in", "Account, technical", "Contract; legitimate interest (security)"],
              ["Take payment, issue licenses, deliver kit files", "Account, orders, licenses", "Contract"],
              ["Verify that a key is used only on its registered places, and block revoked or unpaid licenses", "Licenses, license checks", "Contract; legitimate interest (preventing piracy and fraud)"],
              ["Manage installment plans and unlock a license once fully paid", "Orders, installment records", "Contract"],
              ["Provide support and answer your messages", "Communications, account, licenses", "Contract; legitimate interest"],
              ["Prevent abuse, fraud and attacks (rate limits, 2FA for staff, audit log)", "Technical, admin activity", "Legitimate interest; legal obligation where applicable"],
              ["Remember your language choice", "Language cookie", "Your consent (you can decline it in the cookie banner)"],
              ["Keep financial and tax records", "Orders, payments", "Legal obligation"],
              ["Send service messages (e.g. about your license or a payment)", "Account, orders", "Contract; legitimate interest"],
            ],
          },
        },
        { p: "Where we rely on legitimate interest, we balance it against your rights. You can object to processing based on legitimate interest — see section 9." },
        { p: "We do not use your data for advertising, profiling for marketing, or to make decisions that have legal or similarly significant effects on you based solely on automated processing. The only automated decision is license enforcement: a key is refused when it is revoked, not fully paid, used on an unregistered place, or when its place slots are full. If you think a refusal is wrong, contact us and a person will review it." },
      ],
    },
    {
      id: "cookies",
      title: "5. Cookies and local storage",
      blocks: [
        { p: "We use only a small number of cookies. Essential ones cannot be switched off because the service would not work without them. You can choose “Necessary only” in the cookie banner, and reopen the choice any time from “Cookie settings” in the footer." },
        {
          table: {
            head: ["Name", "Purpose", "Type", "Lifetime"],
            rows: [
              ["__session", "Keeps you signed in (HTTP-only, secure)", "Essential", "Up to 5 days"],
              ["arr_user", "Non-sensitive hint (display name and role) so the menu can render without an extra request", "Essential", "Up to 5 days"],
              ["discord_oauth_state", "Protects the Discord sign-in against forgery", "Essential", "A few minutes"],
              ["__mfa", "Proves a staff member completed two-factor verification", "Essential (staff only)", "12 hours"],
              ["arr_consent", "Remembers your cookie choice", "Essential", "1 year"],
              ["NEXT_LOCALE", "Remembers your chosen language", "Preference — only if you accept", "1 year"],
              ["theme (local storage)", "Light / dark display preference", "Functional", "Until you clear your browser data"],
              ["Firebase auth state (IndexedDB)", "Keeps the live connection to your own license data in the dashboard", "Essential", "While signed in"],
            ],
          },
        },
        { p: "When you open the payment pop-up, Midtrans loads its own scripts and may set its own cookies for fraud prevention and payment processing. Those are governed by Midtrans’ policy." },
        { p: "You can also delete or block cookies in your browser settings. Blocking essential cookies will prevent sign-in." },
      ],
    },
    {
      id: "sharing",
      title: "6. Who we share data with",
      blocks: [
        { p: "We share data only with service providers that help us run ArrStudio, under terms that require them to protect it, and when the law requires. We do not sell personal data and do not share it for cross-context behavioral advertising." },
        {
          table: {
            head: ["Provider", "What they do for us", "Data involved"],
            rows: [
              ["Google (Firebase Authentication, Cloud Firestore)", "Sign-in and our database", "Account, orders, licenses, logs"],
              ["Vercel", "Website hosting, file storage for kit files and videos, request logs", "All web requests, uploaded files"],
              ["Midtrans", "Payment processing (QRIS, virtual accounts, e-wallets, cards)", "Name, email, order and amount; payment details are entered with Midtrans, not us"],
              ["Discord", "“Sign in with Discord” and our support community", "Discord ID, username, avatar, verified email"],
              ["Roblox", "Public place name and icon; license checks come from your game servers", "Place IDs"],
              ["WhatsApp (Meta)", "Custom orders and support, if you message us there", "Your number and messages"],
            ],
          },
        },
        { p: "We may also disclose data if required by law, a court or a competent authority, to enforce our terms, to protect our rights, users or the public, or in a merger, acquisition or sale of assets (you would be told beforehand and the recipient must honour this policy)." },
        { p: "Your license key and registered place IDs are visible only to you, to our administrators and, to the extent needed, to the services listed above. Other customers cannot see them." },
      ],
    },
    {
      id: "transfers",
      title: "7. International transfers",
      blocks: [
        { p: "Our providers operate globally, so your data may be processed in countries other than your own — including Indonesia, the United States, Singapore and other places where Google, Vercel, Midtrans or Discord operate." },
        { p: "Where the law requires, we rely on appropriate safeguards for these transfers, such as the providers’ standard contractual clauses, adequacy decisions, or your consent. Contact us for details." },
      ],
    },
    {
      id: "retention",
      title: "8. How long we keep data",
      blocks: [
        {
          table: {
            head: ["Data", "How long"],
            rows: [
              ["Account profile", "While your account exists. Deleted within 30 days of a verified request, except what we must keep (below)."],
              ["Licenses and bound place IDs", "While the license is active and for up to 3 years after, to handle disputes and re-issues."],
              ["Orders, payments and installment records", "As long as tax and accounting law requires (in Indonesia, generally up to 10 years)."],
              ["License-check data (last check, version, count)", "Stored on the license record for as long as that record exists."],
              ["Sessions and sign-in cookies", "Up to 5 days; 12 hours for staff two-factor status."],
              ["Rate-limit counters", "Automatically deleted within minutes to hours."],
              ["Admin audit log", "At least 24 months, for security and accounting."],
              ["Server and security logs", "Per our hosting provider’s retention (typically days to a few weeks)."],
              ["Support messages", "Up to 3 years after the conversation ends, or until you ask us to delete them."],
            ],
          },
        },
        { p: "When retention ends, we delete or anonymise the data. Backups are overwritten on the provider’s normal cycle." },
      ],
    },
    {
      id: "rights",
      title: "9. Your rights",
      blocks: [
        { p: "Depending on where you live, you have some or all of these rights over your personal data:" },
        {
          ul: [
            "Access — get a copy of the data we hold about you.",
            "Correction — fix data that is wrong or incomplete (you can edit your name and Roblox username in your account).",
            "Deletion — ask us to delete your data, unless we must keep it by law or to defend legal claims.",
            "Restriction and objection — ask us to pause processing, or object to processing based on legitimate interest.",
            "Portability — receive your data in a common, machine-readable format.",
            "Withdraw consent — for example, change your cookie choice at any time. Withdrawal does not affect earlier processing.",
            "Complain — to your data-protection authority.",
          ],
        },
        { p: "To use a right, contact us (section 15). We may ask you to prove you own the account first, and we reply within 30 days (or sooner where the law requires). We do not charge a fee unless a request is clearly excessive." },
        { p: "Regional notes:" },
        {
          ul: [
            "Indonesia — under Law No. 27 of 2022 on Personal Data Protection you may access, correct, delete, restrict, withdraw consent, object to automated processing and claim redress for violations.",
            "European Economic Area and United Kingdom — the GDPR / UK GDPR rights above apply, and you may complain to your local supervisory authority.",
            "California — you have the right to know, delete and correct personal information and to opt out of its sale or sharing. We do not sell or share personal information, and we do not discriminate for exercising these rights.",
            "Philippines (Data Privacy Act 2012), Malaysia (PDPA 2010), Thailand (PDPA 2019) and Vietnam (Decree 13/2023/ND-CP) — you have the access, correction, deletion, objection and consent-withdrawal rights those laws provide, and we honour them.",
          ],
        },
      ],
    },
    {
      id: "security",
      title: "10. How we protect your data",
      blocks: [
        {
          ul: [
            "Encryption in transit (HTTPS with HSTS) on every page and API call.",
            "Passwords are handled by Firebase Authentication and stored as salted hashes; we never see them.",
            "Sessions use HTTP-only, secure, same-site cookies and are checked against Firebase on each request.",
            "Strict access control: the database can be written only by our server, and each customer can read only their own licenses.",
            "Staff accounts require two-factor authentication (authenticator app with backup codes); the two-factor secrets are encrypted at rest.",
            "Rate limiting, anti-replay protection and hashed counters guard sign-in, license checks, discount codes and payments.",
            "Payment confirmations are verified with a cryptographic signature and re-checked directly with Midtrans before any license is issued.",
            "An audit log records administrative actions on money, licenses, roles and pricing.",
            "Kit modules are encrypted and unlock only for valid, paid, registered licenses.",
          ],
        },
        { p: "No system is perfectly secure. If you find a vulnerability, please tell us privately through the contact options below before disclosing it publicly. Keep your password, your license keys and your Roblox place files private." },
        { p: "If a breach affects your personal data and the law requires it, we notify you and the competent authority within the legally required time (for example, 72 hours to the authority under the GDPR, and 3×24 hours under Indonesian law)." },
      ],
    },
    {
      id: "payments",
      title: "11. Payments and installments",
      blocks: [
        { p: "Online payments run through Midtrans. You enter card, bank or e-wallet details on Midtrans’ pages; we receive only the result (paid, pending, failed), the payment method type and the amount." },
        { p: "Installment plans are arranged with us directly. Our team records each confirmed transfer (amount, date, an optional note) against your license. Until the plan is fully paid, your license stays locked: the key is hidden, the kit file cannot be downloaded and the license check fails. Proofs of transfer you send us on Discord or WhatsApp are used only to confirm the payment." },
        { p: "Discount codes you enter are checked on our server and counted against the code’s usage limit; they are not linked to any profile beyond the order they were used on." },
      ],
    },
    {
      id: "children",
      title: "12. Children",
      blocks: [
        { p: "Our service is not directed at children under 13 (or the higher minimum age of digital consent in your country, such as 16 in parts of the EU). We do not knowingly collect their data. If you are a parent or guardian and believe a child gave us personal data, contact us and we will delete it." },
        { p: "Many Roblox creators are teenagers. If you are under the age of majority where you live, please make purchases with a parent or guardian’s permission." },
      ],
    },
    {
      id: "thirdparty",
      title: "13. Links and third-party services",
      blocks: [
        { p: "Our site links to Discord, WhatsApp, Roblox and sample sites we built. When you follow a link, the other service’s policy applies. We are not responsible for their content or practices." },
        { p: "Kits you install in your own Roblox game run on your servers. Any data about your players that your game collects is yours to manage; our kits send us only the license-check data described in section 3." },
      ],
    },
    {
      id: "changes",
      title: "14. Changes to this policy",
      blocks: [
        { p: "We may update this policy as the service changes or the law requires. The “last updated” date at the top shows the current version. For material changes we will give clear notice — for example a message in your dashboard or on Discord — and, where consent is required, ask for it again." },
      ],
    },
    {
      id: "contact",
      title: "15. Contact us",
      blocks: [
        { p: `For privacy questions or to use your rights, reach ${LEGAL.controller} through any of these channels. Please include the email on your account and what you would like us to do.` },
      ],
    },
  ],
};

const id: Policy = {
  title: "Kebijakan Privasi",
  subtitle: "Data apa yang kami kumpulkan, untuk apa, siapa yang bisa melihatnya, dan pilihan yang kamu punya — dengan bahasa yang jelas.",
  updatedLabel: "Terakhir diperbarui",
  tocLabel: "Di halaman ini",
  backLabel: "Kembali ke situs",
  contactLabels: { discord: "Discord (tiket bantuan)", whatsapp: "WhatsApp", email: "Email" },
  sections: [
    {
      id: "summary",
      title: "1. Versi singkat",
      blocks: [
        { p: "ArrStudio menjual kit Roblox berlisensi. Agar layanan ini berjalan, kami butuh akun, cara menerima pembayaran, dan cara memastikan key lisensi hanya dipakai di place yang terdaftar. Kebijakan ini menjelaskan data pribadi yang terlibat." },
        {
          ul: [
            "Kami mengumpulkan seperlunya: data akun, pesanan dan lisensi, serta data teknis untuk menjaga keamanan layanan.",
            "Kami tidak menjual data pribadimu dan tidak membagikannya untuk iklan. Tidak ada cookie iklan atau pelacak di situs ini.",
            "Pembayaran diproses oleh Midtrans. Kami tidak pernah melihat atau menyimpan nomor kartu atau kredensial e-wallet-mu.",
            "Kamu bisa meminta akses, koreksi, atau penghapusan data kapan saja (bagian 9).",
          ],
        },
      ],
    },
    {
      id: "who",
      title: "2. Siapa kami dan cakupan kebijakan ini",
      blocks: [
        { p: `${LEGAL.controller} (“ArrStudio”, “kami”) adalah pengendali data pribadi yang dijelaskan di sini. Kebijakan ini mencakup situs web, dasbor pelanggan, alat admin yang kami pakai untuk menjalankan layanan, API pengecekan lisensi yang dipanggil kit Roblox kami, serta kanal pembelian dan bantuan kami.` },
        { p: "Kebijakan ini tidak mencakup layanan pihak ketiga yang kami tautkan atau yang kamu pakai bersama layanan kami (Roblox, Discord, WhatsApp, bankmu). Mereka punya kebijakan sendiri yang sebaiknya kamu baca." },
      ],
    },
    {
      id: "collect",
      title: "3. Data yang kami kumpulkan",
      blocks: [
        { p: "Kami mengumpulkan data dengan tiga cara: yang kamu berikan, yang tercipta saat kamu memakai layanan, dan yang berasal dari layanan yang kamu hubungkan." },
        {
          table: {
            head: ["Kategori", "Isinya", "Sumber"],
            rows: [
              ["Akun", "Alamat email, nama tampilan, username Roblox (opsional), ID akun unik, cara mendaftar, dan password (hanya disimpan sebagai hash oleh Firebase Authentication — kami tidak bisa membacanya).", "Kamu"],
              ["Login Discord", "Jika masuk dengan Discord: ID pengguna, username, URL avatar, dan email bila terverifikasi.", "Discord, dengan izinmu"],
              ["Pesanan & pembayaran", "Apa yang dibeli, harga, kode diskon yang dipakai, jenis metode bayar (mis. QRIS, transfer bank), status, dan waktu. Untuk cicilan: total, jumlah yang sudah dibayar, tanggal, dan catatan yang dicatat tim kami setelah mengecek bukti transfer.", "Kamu / Midtrans / tim kami"],
              ["Bukti transfer", "Jika kamu mengirim bukti transfer lewat Discord atau WhatsApp: gambar atau pesan yang kamu kirim, yang mungkin memuat namamu dan data rekening.", "Kamu"],
              ["Lisensi", "Key lisensi, kit, ID place Roblox yang terikat ke key, jumlah slot place, tanggal terbit, dan status.", "Dibuat oleh kami / kamu"],
              ["Pengecekan lisensi", "Tiap server game dijalankan, kit memanggil API lisensi. Kami menerima key, ID kit, versi kit, ID place dan ID job server Roblox, serta alamat IP servermu. Kami hanya menyimpan waktu cek terakhir, versi, dan jumlah total — bukan riwayat lengkap.", "Server game Roblox-mu"],
              ["Teknis & keamanan", "Alamat IP, jenis browser dan perangkat, halaman yang diminta, waktu, log error; penghitung batas request (disimpan dengan kunci ter-hash); laporan pelanggaran content-security-policy.", "Otomatis"],
              ["Aktivitas admin", "Untuk akun staf kami: catatan tindakan administratif (siapa melakukan apa dan kapan).", "Otomatis"],
              ["Komunikasi", "Pesan yang kamu kirim di Discord atau WhatsApp, beserta identitas Discord / WhatsApp-mu.", "Kamu"],
            ],
          },
        },
        { p: "Kami tidak sengaja mengumpulkan data pribadi sensitif (seperti data kesehatan, biometrik, atau politik), dan kami tidak meminta KTP atau identitas resmi." },
        { note: "Thumbnail dan nama place Roblox di dasbormu diambil dari API publik Roblox memakai ID place yang kamu daftarkan. Kami tidak menerima data lain tentang akun Roblox-mu." },
      ],
    },
    {
      id: "use",
      title: "4. Untuk apa data dipakai (dan dasar hukumnya)",
      blocks: [
        {
          table: {
            head: ["Tujuan", "Data yang dipakai", "Dasar hukum"],
            rows: [
              ["Membuat dan mengamankan akun, memasukkanmu", "Akun, teknis", "Perjanjian; kepentingan yang sah (keamanan)"],
              ["Menerima pembayaran, menerbitkan lisensi, mengirim file kit", "Akun, pesanan, lisensi", "Perjanjian"],
              ["Memastikan key hanya dipakai di place terdaftar, dan menolak lisensi yang dicabut atau belum lunas", "Lisensi, pengecekan lisensi", "Perjanjian; kepentingan yang sah (mencegah pembajakan dan penipuan)"],
              ["Mengelola cicilan dan membuka lisensi setelah lunas", "Pesanan, catatan cicilan", "Perjanjian"],
              ["Memberi bantuan dan membalas pesanmu", "Komunikasi, akun, lisensi", "Perjanjian; kepentingan yang sah"],
              ["Mencegah penyalahgunaan, penipuan, dan serangan (batas request, 2FA staf, audit log)", "Teknis, aktivitas admin", "Kepentingan yang sah; kewajiban hukum bila berlaku"],
              ["Mengingat bahasa pilihanmu", "Cookie bahasa", "Persetujuanmu (bisa ditolak di banner cookie)"],
              ["Menyimpan catatan keuangan dan pajak", "Pesanan, pembayaran", "Kewajiban hukum"],
              ["Mengirim pesan layanan (mis. soal lisensi atau pembayaran)", "Akun, pesanan", "Perjanjian; kepentingan yang sah"],
            ],
          },
        },
        { p: "Bila kami mengandalkan kepentingan yang sah, kami menimbangnya terhadap hakmu. Kamu boleh keberatan atas pemrosesan berdasarkan kepentingan yang sah — lihat bagian 9." },
        { p: "Kami tidak memakai datamu untuk iklan, pembuatan profil untuk pemasaran, atau keputusan yang berdampak hukum atau signifikan bagimu yang semata-mata berdasarkan pemrosesan otomatis. Satu-satunya keputusan otomatis adalah penegakan lisensi: key ditolak bila dicabut, belum lunas, dipakai di place yang tidak terdaftar, atau slot place-nya penuh. Jika kamu merasa penolakan itu keliru, hubungi kami dan seorang staf akan meninjaunya." },
      ],
    },
    {
      id: "cookies",
      title: "5. Cookie dan penyimpanan lokal",
      blocks: [
        { p: "Kami hanya memakai sedikit cookie. Cookie penting tidak bisa dimatikan karena layanan tidak akan berjalan tanpanya. Kamu bisa memilih “Hanya yang penting” di banner cookie, dan membuka kembali pilihan itu kapan saja lewat “Pengaturan cookie” di footer." },
        {
          table: {
            head: ["Nama", "Fungsi", "Jenis", "Masa berlaku"],
            rows: [
              ["__session", "Menjaga kamu tetap masuk (HTTP-only, secure)", "Penting", "Hingga 5 hari"],
              ["arr_user", "Petunjuk tidak sensitif (nama tampilan dan peran) agar menu tampil tanpa request tambahan", "Penting", "Hingga 5 hari"],
              ["discord_oauth_state", "Melindungi login Discord dari pemalsuan", "Penting", "Beberapa menit"],
              ["__mfa", "Menandai staf sudah lolos verifikasi dua langkah", "Penting (khusus staf)", "12 jam"],
              ["arr_consent", "Mengingat pilihan cookie-mu", "Penting", "1 tahun"],
              ["NEXT_LOCALE", "Mengingat bahasa pilihanmu", "Preferensi — hanya jika kamu setuju", "1 tahun"],
              ["theme (local storage)", "Preferensi tampilan terang / gelap", "Fungsional", "Sampai data browser dihapus"],
              ["Status login Firebase (IndexedDB)", "Menjaga koneksi langsung ke data lisensimu di dasbor", "Penting", "Selama masuk"],
            ],
          },
        },
        { p: "Saat jendela pembayaran terbuka, Midtrans memuat skripnya sendiri dan mungkin memasang cookie sendiri untuk pencegahan penipuan dan pemrosesan pembayaran. Itu diatur oleh kebijakan Midtrans." },
        { p: "Kamu juga bisa menghapus atau memblokir cookie lewat pengaturan browser. Memblokir cookie penting akan membuatmu tidak bisa masuk." },
      ],
    },
    {
      id: "sharing",
      title: "6. Dengan siapa data dibagikan",
      blocks: [
        { p: "Kami hanya membagikan data kepada penyedia layanan yang membantu menjalankan ArrStudio, dengan ketentuan yang mewajibkan mereka melindunginya, dan bila diwajibkan hukum. Kami tidak menjual data pribadi dan tidak membagikannya untuk iklan perilaku lintas konteks." },
        {
          table: {
            head: ["Penyedia", "Peran untuk kami", "Data terkait"],
            rows: [
              ["Google (Firebase Authentication, Cloud Firestore)", "Login dan basis data kami", "Akun, pesanan, lisensi, log"],
              ["Vercel", "Hosting situs, penyimpanan file kit dan video, log request", "Semua request web, file yang diunggah"],
              ["Midtrans", "Pemrosesan pembayaran (QRIS, virtual account, e-wallet, kartu)", "Nama, email, pesanan, dan nominal; detail pembayaran dimasukkan di Midtrans, bukan di kami"],
              ["Discord", "“Masuk dengan Discord” dan komunitas bantuan kami", "ID Discord, username, avatar, email terverifikasi"],
              ["Roblox", "Nama dan ikon place yang publik; pengecekan lisensi datang dari server game-mu", "ID place"],
              ["WhatsApp (Meta)", "Pesanan khusus dan bantuan, bila kamu menghubungi kami di sana", "Nomormu dan pesan"],
            ],
          },
        },
        { p: "Kami juga dapat mengungkapkan data bila diwajibkan oleh hukum, pengadilan, atau otoritas berwenang, untuk menegakkan ketentuan kami, melindungi hak kami, pengguna, atau publik, atau dalam merger, akuisisi, atau penjualan aset (kamu akan diberi tahu lebih dulu dan penerimanya wajib menghormati kebijakan ini)." },
        { p: "Key lisensi dan ID place yang terdaftar hanya terlihat oleh kamu, administrator kami, dan, sebatas yang diperlukan, layanan yang tercantum di atas. Pelanggan lain tidak bisa melihatnya." },
      ],
    },
    {
      id: "transfers",
      title: "7. Transfer data ke luar negeri",
      blocks: [
        { p: "Penyedia kami beroperasi secara global, sehingga datamu dapat diproses di negara selain negaramu — termasuk Indonesia, Amerika Serikat, Singapura, dan tempat lain tempat Google, Vercel, Midtrans, atau Discord beroperasi." },
        { p: "Bila hukum mewajibkan, kami mengandalkan pengamanan yang memadai untuk transfer ini, seperti klausul kontrak standar penyedia, keputusan kecukupan, atau persetujuanmu. Hubungi kami untuk rinciannya." },
      ],
    },
    {
      id: "retention",
      title: "8. Berapa lama data disimpan",
      blocks: [
        {
          table: {
            head: ["Data", "Berapa lama"],
            rows: [
              ["Profil akun", "Selama akunmu ada. Dihapus dalam 30 hari sejak permintaan terverifikasi, kecuali yang wajib kami simpan (di bawah)."],
              ["Lisensi dan ID place terikat", "Selama lisensi aktif dan hingga 3 tahun sesudahnya, untuk menangani sengketa dan penerbitan ulang."],
              ["Pesanan, pembayaran, dan catatan cicilan", "Selama diwajibkan hukum pajak dan akuntansi (di Indonesia umumnya hingga 10 tahun)."],
              ["Data pengecekan lisensi (cek terakhir, versi, jumlah)", "Disimpan di catatan lisensi selama catatan itu ada."],
              ["Sesi dan cookie login", "Hingga 5 hari; 12 jam untuk status verifikasi dua langkah staf."],
              ["Penghitung batas request", "Dihapus otomatis dalam hitungan menit sampai jam."],
              ["Audit log admin", "Minimal 24 bulan, untuk keamanan dan akuntansi."],
              ["Log server dan keamanan", "Sesuai retensi penyedia hosting (biasanya beberapa hari sampai beberapa minggu)."],
              ["Pesan bantuan", "Hingga 3 tahun setelah percakapan selesai, atau sampai kamu meminta penghapusan."],
            ],
          },
        },
        { p: "Setelah masa simpan berakhir, kami menghapus atau menganonimkan data. Cadangan ditimpa mengikuti siklus normal penyedia." },
      ],
    },
    {
      id: "rights",
      title: "9. Hakmu",
      blocks: [
        { p: "Tergantung tempat tinggalmu, kamu punya sebagian atau seluruh hak berikut atas data pribadimu:" },
        {
          ul: [
            "Akses — mendapat salinan data yang kami simpan tentangmu.",
            "Koreksi — memperbaiki data yang salah atau tidak lengkap (nama dan username Roblox bisa kamu ubah sendiri di akun).",
            "Penghapusan — meminta datamu dihapus, kecuali wajib kami simpan menurut hukum atau untuk membela klaim hukum.",
            "Pembatasan dan keberatan — meminta pemrosesan dihentikan sementara, atau keberatan atas pemrosesan berdasarkan kepentingan yang sah.",
            "Portabilitas — menerima datamu dalam format umum yang dapat dibaca mesin.",
            "Menarik persetujuan — misalnya mengubah pilihan cookie kapan saja. Penarikan tidak memengaruhi pemrosesan sebelumnya.",
            "Mengajukan keluhan — ke otoritas perlindungan data di negaramu.",
          ],
        },
        { p: "Untuk menggunakan hak, hubungi kami (bagian 15). Kami mungkin meminta bukti bahwa kamu pemilik akun lebih dulu, dan membalas dalam 30 hari (atau lebih cepat bila hukum mewajibkan). Kami tidak memungut biaya kecuali permintaannya jelas berlebihan." },
        { p: "Catatan per wilayah:" },
        {
          ul: [
            "Indonesia — menurut UU No. 27 Tahun 2022 tentang Pelindungan Data Pribadi, kamu berhak mengakses, memperbaiki, menghapus, membatasi, menarik persetujuan, keberatan atas pemrosesan otomatis, dan menuntut ganti rugi atas pelanggaran.",
            "Wilayah Ekonomi Eropa dan Inggris — hak GDPR / UK GDPR di atas berlaku, dan kamu dapat mengajukan keluhan ke otoritas pengawas setempat.",
            "California — kamu berhak mengetahui, menghapus, dan mengoreksi informasi pribadi serta menolak penjualan atau pembagiannya. Kami tidak menjual atau membagikan informasi pribadi, dan tidak mendiskriminasi pengguna yang menggunakan hak ini.",
            "Filipina (Data Privacy Act 2012), Malaysia (PDPA 2010), Thailand (PDPA 2019), dan Vietnam (Decree 13/2023/ND-CP) — kamu punya hak akses, koreksi, penghapusan, keberatan, dan penarikan persetujuan sesuai undang-undang tersebut, dan kami menghormatinya.",
          ],
        },
      ],
    },
    {
      id: "security",
      title: "10. Cara kami melindungi datamu",
      blocks: [
        {
          ul: [
            "Enkripsi saat transit (HTTPS dengan HSTS) di setiap halaman dan panggilan API.",
            "Password dikelola Firebase Authentication dan disimpan sebagai hash; kami tidak pernah melihatnya.",
            "Sesi memakai cookie HTTP-only, secure, same-site, dan diperiksa ke Firebase pada setiap request.",
            "Kontrol akses ketat: basis data hanya bisa ditulis oleh server kami, dan tiap pelanggan hanya bisa membaca lisensinya sendiri.",
            "Akun staf wajib autentikasi dua langkah (aplikasi authenticator dengan kode cadangan); rahasia dua langkah dienkripsi saat disimpan.",
            "Pembatasan request, perlindungan anti-replay, dan penghitung ter-hash menjaga login, pengecekan lisensi, kode diskon, dan pembayaran.",
            "Konfirmasi pembayaran diverifikasi dengan tanda tangan kriptografis dan dicek ulang langsung ke Midtrans sebelum lisensi diterbitkan.",
            "Audit log mencatat tindakan administratif atas uang, lisensi, peran, dan harga.",
            "Modul kit dienkripsi dan hanya terbuka untuk lisensi yang valid, lunas, dan terdaftar.",
          ],
        },
        { p: "Tidak ada sistem yang sepenuhnya aman. Jika kamu menemukan celah keamanan, mohon beri tahu kami secara privat lewat kontak di bawah sebelum mengungkapkannya ke publik. Jaga kerahasiaan password, key lisensi, dan file place Roblox-mu." },
        { p: "Bila terjadi kebocoran yang memengaruhi data pribadimu dan hukum mewajibkannya, kami memberi tahu kamu dan otoritas berwenang dalam waktu yang diwajibkan (misalnya 72 jam kepada otoritas menurut GDPR, dan 3×24 jam menurut hukum Indonesia)." },
      ],
    },
    {
      id: "payments",
      title: "11. Pembayaran dan cicilan",
      blocks: [
        { p: "Pembayaran online berjalan lewat Midtrans. Kamu memasukkan detail kartu, bank, atau e-wallet di halaman Midtrans; kami hanya menerima hasilnya (lunas, menunggu, gagal), jenis metode bayar, dan nominal." },
        { p: "Cicilan diatur langsung dengan kami. Tim kami mencatat setiap transfer yang sudah dikonfirmasi (nominal, tanggal, catatan opsional) pada lisensimu. Sebelum cicilan lunas, lisensimu terkunci: key disembunyikan, file kit tidak bisa diunduh, dan pengecekan lisensi gagal. Bukti transfer yang kamu kirim di Discord atau WhatsApp hanya dipakai untuk mengonfirmasi pembayaran." },
        { p: "Kode diskon yang kamu masukkan diperiksa di server kami dan dihitung terhadap batas pemakaian kode; kode itu tidak dikaitkan dengan profil apa pun selain pesanan tempat kode dipakai." },
      ],
    },
    {
      id: "children",
      title: "12. Anak-anak",
      blocks: [
        { p: "Layanan kami tidak ditujukan bagi anak di bawah 13 tahun (atau usia minimum persetujuan digital yang lebih tinggi di negaramu, misalnya 16 tahun di sebagian Uni Eropa). Kami tidak dengan sengaja mengumpulkan data mereka. Jika kamu orang tua atau wali dan yakin anak memberi kami data pribadi, hubungi kami dan kami akan menghapusnya." },
        { p: "Banyak kreator Roblox masih remaja. Jika usiamu di bawah usia dewasa di tempatmu tinggal, mohon membeli dengan izin orang tua atau wali." },
      ],
    },
    {
      id: "thirdparty",
      title: "13. Tautan dan layanan pihak ketiga",
      blocks: [
        { p: "Situs kami menautkan ke Discord, WhatsApp, Roblox, dan situs contoh buatan kami. Saat kamu mengikuti tautan, kebijakan layanan lain itulah yang berlaku. Kami tidak bertanggung jawab atas isi atau praktiknya." },
        { p: "Kit yang kamu pasang di game Roblox-mu berjalan di servermu. Data pemain yang dikumpulkan game-mu menjadi tanggung jawabmu; kit kami hanya mengirim data pengecekan lisensi seperti dijelaskan di bagian 3." },
      ],
    },
    {
      id: "changes",
      title: "14. Perubahan kebijakan",
      blocks: [
        { p: "Kami dapat memperbarui kebijakan ini seiring perubahan layanan atau tuntutan hukum. Tanggal “terakhir diperbarui” di atas menunjukkan versi terkini. Untuk perubahan penting, kami memberi pemberitahuan yang jelas — misalnya pesan di dasbor atau Discord — dan, bila perlu persetujuan, meminta lagi." },
      ],
    },
    {
      id: "contact",
      title: "15. Hubungi kami",
      blocks: [
        { p: `Untuk pertanyaan privasi atau menggunakan hakmu, hubungi ${LEGAL.controller} lewat salah satu kanal berikut. Sertakan email akunmu dan apa yang kamu inginkan.` },
      ],
    },
  ],
};

export const policies = { en, id } as const;
export type PolicyLang = keyof typeof policies;
export const policyLang = (v: unknown): PolicyLang => (v === "id" ? "id" : "en");
