import { LEGAL, type Policy } from "../shared";

const en: Policy = {
  title: "Privacy Policy",
  subtitle: "What we collect, why we collect it, who sees it, and the choices you have — in plain language.",
  updatedLabel: "Last updated",
  tocLabel: "On this page",
  backLabel: "Back to site",
  contactLabels: { discord: "Discord (support ticket)", whatsapp: "WhatsApp", email: "Email" },
  sections: [
    {
      id: "summary",
      title: "1. The short version",
      blocks: [
        { p: "ArrStudio sells licensed Roblox kits. To run that service we need an account, a way to take payment, and a way to check that a license key is used on the places it was bought for. This policy explains the personal data involved." },
        {
          ul: [
            "We collect the minimum needed: your account details, your orders and licenses, and the technical data needed to keep the service secure.",
            "We do not sell your personal data, and we do not share it for advertising. There are no ad or tracking cookies on this site.",
            "Payments are handled by Midtrans. We never see or store your card number or e-wallet credentials.",
            "You can export your data and delete your account yourself in Dashboard → Account, or ask us to do it (section 9).",
          ],
        },
      ],
    },
    {
      id: "who",
      title: "2. Who we are and what this policy covers",
      blocks: [
        { p: `${LEGAL.controller} (“ArrStudio”, “we”, “us”) is the controller of the personal data described here. This policy covers the website, the customer dashboard, the admin tools we use to run the service, the license-check API called by our Roblox kits, and our purchase and support channels.` },
        { p: "It does not cover third-party services that we link to or that you use alongside ours (Roblox, Discord, WhatsApp, your bank). Those have their own policies, and you should read them." },
      ],
    },
    {
      id: "collect",
      title: "3. The data we collect",
      blocks: [
        { p: "We collect data in three ways: what you give us, what is created when you use the service, and what comes from services you connect." },
        {
          table: {
            head: ["Category", "What it includes", "Source"],
            rows: [
              ["Account", "Email address, display name, optional Roblox username, a unique account ID, sign-up method, and a password (stored only as a salted hash by Firebase Authentication — we cannot read it).", "You"],
              ["Discord login", "If you sign in with Discord: Discord user ID, username, avatar URL and, when verified, your email address.", "Discord, with your permission"],
              ["Orders & payments", "What you bought, price, discount code used, payment method type (e.g. QRIS, bank transfer), status and timestamps. For installment plans: total, amounts paid, dates and notes recorded by our team after checking a transfer proof.", "You / Midtrans / our team"],
              ["Transfer proofs", "If you send a proof of transfer through Discord or WhatsApp: the image or message you send, which may show your name and account details.", "You"],
              ["QRIS payments", "If you pay by QRIS, the payer name and amount appear in our merchant account (GoPay Merchant) and on your bank statement. We use them only to match your payment.", "You / your bank or e-wallet"],
              ["Licenses", "License keys, the kit, the Roblox place IDs the key is bound to, number of place slots, issue date and status.", "Generated by us / you"],
              ["License checks", "Each time a game server starts, our kit calls the license API. We receive the key, kit ID, kit version, the Roblox place ID and server job ID, and your server's IP address. We keep only the latest check time, version and a running count — not a full history.", "Your Roblox game servers"],
              ["Technical & security", "IP address, browser and device type, pages requested, timestamps and error logs; rate-limit counters (stored under a hashed key); content-security-policy violation reports.", "Automatically"],
              ["Admin activity", "For our own staff accounts: a log of administrative actions (who did what and when).", "Automatically"],
              ["Communications", "Messages you send us on Discord or WhatsApp, and your Discord / WhatsApp identifiers.", "You"],
            ],
          },
        },
        { p: "We do not intentionally collect sensitive personal data (such as health, biometric or political data), and we do not ask for government ID." },
        { note: "Roblox thumbnails and place names shown in your dashboard are fetched from Roblox’s public APIs using the place IDs you registered. We do not receive any other data about your Roblox account." },
      ],
    },
    {
      id: "use",
      title: "4. Why we use your data (and our legal basis)",
      blocks: [
        {
          table: {
            head: ["Purpose", "Data used", "Legal basis"],
            rows: [
              ["Create and secure your account, sign you in", "Account, technical", "Contract; legitimate interest (security)"],
              ["Take payment, issue licenses, deliver kit files", "Account, orders, licenses", "Contract"],
              ["Verify that a key is used only on its registered places, and block revoked or unpaid licenses", "Licenses, license checks", "Contract; legitimate interest (preventing piracy and fraud)"],
              ["Manage installment plans and unlock a license once fully paid", "Orders, installment records", "Contract"],
              ["Provide support and answer your messages", "Communications, account, licenses", "Contract; legitimate interest"],
              ["Prevent abuse, fraud and attacks (rate limits, 2FA for staff, audit log)", "Technical, admin activity", "Legitimate interest; legal obligation where applicable"],
              ["Remember your language choice", "Language cookie", "Your consent (you can decline it in the cookie banner)"],
              ["Keep financial and tax records", "Orders, payments", "Legal obligation"],
              ["Send service messages (e.g. about your license or a payment)", "Account, orders", "Contract; legitimate interest"],
            ],
          },
        },
        { p: "Where we rely on legitimate interest, we balance it against your rights. You can object to processing based on legitimate interest — see section 9." },
        { p: "We do not use your data for advertising, profiling for marketing, or to make decisions that have legal or similarly significant effects on you based solely on automated processing. The only automated decision is license enforcement: a key is refused when it is revoked, not fully paid, used on an unregistered place, or when its place slots are full. If you think a refusal is wrong, contact us and a person will review it." },
      ],
    },
    {
      id: "cookies",
      title: "5. Cookies and local storage",
      blocks: [
        { p: "We use only a small number of cookies. Essential ones cannot be switched off because the service would not work without them. You can choose “Necessary only” in the cookie banner, and reopen the choice any time from “Cookie settings” in the footer." },
        {
          table: {
            head: ["Name", "Purpose", "Type", "Lifetime"],
            rows: [
              ["__session", "Keeps you signed in (HTTP-only, secure)", "Essential", "Up to 5 days"],
              ["arr_user", "Non-sensitive hint (display name and role) so the menu can render without an extra request", "Essential", "Up to 5 days"],
              ["discord_oauth_state", "Protects the Discord sign-in against forgery", "Essential", "A few minutes"],
              ["__mfa", "Proves a staff member completed two-factor verification", "Essential (staff only)", "12 hours"],
              ["arr_consent", "Remembers your cookie choice", "Essential", "1 year"],
              ["NEXT_LOCALE", "Remembers your chosen language", "Preference — only if you accept", "1 year"],
              ["theme (local storage)", "Light / dark display preference", "Functional", "Until you clear your browser data"],
              ["Firebase auth state (IndexedDB)", "Keeps the live connection to your own license data in the dashboard", "Essential", "While signed in"],
            ],
          },
        },
        { p: "When you open the payment pop-up, Midtrans loads its own scripts and may set its own cookies for fraud prevention and payment processing. Those are governed by Midtrans’ policy." },
        { p: "You can also delete or block cookies in your browser settings. Blocking essential cookies will prevent sign-in." },
      ],
    },
    {
      id: "sharing",
      title: "6. Who we share data with",
      blocks: [
        { p: "We share data only with service providers that help us run ArrStudio, under terms that require them to protect it, and when the law requires. We do not sell personal data and do not share it for cross-context behavioral advertising." },
        {
          table: {
            head: ["Provider", "What they do for us", "Data involved"],
            rows: [
              ["Google (Firebase Authentication, Cloud Firestore)", "Sign-in and our database", "Account, orders, licenses, logs"],
              ["Vercel", "Website hosting, file storage for kit files and videos, request logs", "All web requests, uploaded files"],
              ["Midtrans", "Payment processing (QRIS, virtual accounts, e-wallets, cards)", "Name, email, order and amount; payment details are entered with Midtrans, not us"],
              ["GoPay Merchant (QRIS)", "Receives QRIS payments made to our merchant account", "Payer name and amount shown with the transfer"],
              ["Discord", "“Sign in with Discord” and our support community", "Discord ID, username, avatar, verified email"],
              ["Roblox", "Public place name and icon; license checks come from your game servers", "Place IDs"],
              ["WhatsApp (Meta)", "Custom orders and support, if you message us there", "Your number and messages"],
            ],
          },
        },
        { p: "We may also disclose data if required by law, a court or a competent authority, to enforce our terms, to protect our rights, users or the public, or in a merger, acquisition or sale of assets (you would be told beforehand and the recipient must honour this policy)." },
        { p: "Your license key and registered place IDs are visible only to you, to our administrators and, to the extent needed, to the services listed above. Other customers cannot see them." },
      ],
    },
    {
      id: "transfers",
      title: "7. International transfers",
      blocks: [
        { p: "Our providers operate globally, so your data may be processed in countries other than your own — including Indonesia, the United States, Singapore and other places where Google, Vercel, Midtrans or Discord operate." },
        { p: "Where the law requires, we rely on appropriate safeguards for these transfers, such as the providers’ standard contractual clauses, adequacy decisions, or your consent. Contact us for details." },
      ],
    },
    {
      id: "retention",
      title: "8. How long we keep data",
      blocks: [
        {
          table: {
            head: ["Data", "How long"],
            rows: [
              ["Account profile", "While your account exists. Deleted immediately when you delete your account in Dashboard → Account (or within 30 days if you ask us)."],
              ["Licenses and bound place IDs", "While the license is active. After you delete your account the license is revoked and kept without your email or ID for up to 3 years, to handle disputes."],
              ["Orders, payments and installment records", "As long as tax and accounting law requires (in Indonesia, generally up to 10 years). After account deletion they are kept without your identity."],
              ["License-check data (last check, version, count)", "Stored on the license record for as long as that record exists."],
              ["Sessions and sign-in cookies", "Up to 5 days; 12 hours for staff two-factor status."],
              ["Rate-limit counters", "Automatically deleted within minutes to hours."],
              ["Admin audit log", "At least 24 months, for security and accounting."],
              ["Server and security logs", "Per our hosting provider’s retention (typically days to a few weeks)."],
              ["Support messages", "Up to 3 years after the conversation ends, or until you ask us to delete them."],
            ],
          },
        },
        { p: "When retention ends, we delete or anonymise the data. Backups are overwritten on the provider’s normal cycle." },
      ],
    },
    {
      id: "rights",
      title: "9. Your rights",
      blocks: [
        { p: "Depending on where you live, you have some or all of these rights over your personal data:" },
        {
          ul: [
            "Access — get a copy of the data we hold about you.",
            "Correction — fix data that is wrong or incomplete (you can edit your name and Roblox username in your account).",
            "Deletion — delete your account yourself in Dashboard → Account, or ask us. We keep only what the law requires or what we need to defend legal claims (section 8).",
            "Restriction and objection — ask us to pause processing, or object to processing based on legitimate interest.",
            "Portability — download your data as a JSON file from Dashboard → Account, or ask us.",
            "Withdraw consent — for example, change your cookie choice at any time. Withdrawal does not affect earlier processing.",
            "Complain — to your data-protection authority.",
          ],
        },
        { p: "Export and account deletion work instantly from your dashboard. For any other request, contact us (section 15). We may ask you to prove you own the account first, and we reply within 30 days (or sooner where the law requires). We do not charge a fee unless a request is clearly excessive." },
        { p: "Regional notes:" },
        {
          ul: [
            "Indonesia — under Law No. 27 of 2022 on Personal Data Protection you may access, correct, delete, restrict, withdraw consent, object to automated processing and claim redress for violations.",
            "European Economic Area and United Kingdom — the GDPR / UK GDPR rights above apply, and you may complain to your local supervisory authority.",
            "California — you have the right to know, delete and correct personal information and to opt out of its sale or sharing. We do not sell or share personal information, and we do not discriminate for exercising these rights.",
            "Philippines (Data Privacy Act 2012), Malaysia (PDPA 2010), Thailand (PDPA 2019) and Vietnam (Decree 13/2023/ND-CP) — you have the access, correction, deletion, objection and consent-withdrawal rights those laws provide, and we honour them.",
          ],
        },
      ],
    },
    {
      id: "security",
      title: "10. How we protect your data",
      blocks: [
        {
          ul: [
            "Encryption in transit (HTTPS with HSTS) on every page and API call.",
            "Passwords are handled by Firebase Authentication and stored as salted hashes; we never see them.",
            "Sessions use HTTP-only, secure, same-site cookies and are checked against Firebase on each request.",
            "Strict access control: the database can be written only by our server, and each customer can read only their own licenses.",
            "Staff accounts require two-factor authentication (authenticator app with backup codes); the two-factor secrets are encrypted at rest.",
            "Rate limiting, anti-replay protection and hashed counters guard sign-in, license checks, discount codes and payments.",
            "Payment confirmations are verified with a cryptographic signature and re-checked directly with Midtrans before any license is issued.",
            "An audit log records administrative actions on money, licenses, roles and pricing.",
            "Kit modules are encrypted and unlock only for valid, paid, registered licenses.",
          ],
        },
        { p: "No system is perfectly secure. If you find a vulnerability, please tell us privately through the contact options below before disclosing it publicly. Keep your password, your license keys and your Roblox place files private." },
        { p: "If a breach affects your personal data and the law requires it, we notify you and the competent authority within the legally required time (for example, 72 hours to the authority under the GDPR, and 3×24 hours under Indonesian law)." },
      ],
    },
    {
      id: "payments",
      title: "11. Payments and installments",
      blocks: [
        { p: "Online payments run through Midtrans. You enter card, bank or e-wallet details on Midtrans’ pages; we receive only the result (paid, pending, failed), the payment method type and the amount." },
        { p: "You can also pay by QRIS to our merchant account (GoPay Merchant). The payer name and amount are visible to us in that account; we match the payment to your order using the transfer proof you send us, and use that information for nothing else." },
        { p: "Installment plans are arranged with us directly. Our team records each confirmed transfer (amount, date, an optional note) against your license. Until the plan is fully paid, your license stays locked: the key is hidden, the kit file cannot be downloaded and the license check fails. Proofs of transfer you send us on Discord or WhatsApp are used only to confirm the payment." },
        { p: "Discount codes you enter are checked on our server and counted against the code’s usage limit; they are not linked to any profile beyond the order they were used on." },
      ],
    },
    {
      id: "children",
      title: "12. Children",
      blocks: [
        { p: "Our service is not directed at children under 13 (or the higher minimum age of digital consent in your country, such as 16 in parts of the EU). We do not knowingly collect their data. If you are a parent or guardian and believe a child gave us personal data, contact us and we will delete it." },
        { p: "Many Roblox creators are teenagers. If you are under the age of majority where you live, please make purchases with a parent or guardian’s permission." },
      ],
    },
    {
      id: "thirdparty",
      title: "13. Links and third-party services",
      blocks: [
        { p: "Our site links to Discord, WhatsApp, Roblox and sample sites we built. When you follow a link, the other service’s policy applies. We are not responsible for their content or practices." },
        { p: "Kits you install in your own Roblox game run on your servers. Any data about your players that your game collects is yours to manage; our kits send us only the license-check data described in section 3." },
      ],
    },
    {
      id: "changes",
      title: "14. Changes to this policy",
      blocks: [
        { p: "We may update this policy as the service changes or the law requires. The “last updated” date at the top shows the current version. For material changes we will give clear notice — for example a message in your dashboard or on Discord — and, where consent is required, ask for it again." },
      ],
    },
    {
      id: "contact",
      title: "15. Contact us",
      blocks: [
        { p: `For privacy questions or to use your rights, reach ${LEGAL.controller} through any of these channels. Please include the email on your account and what you would like us to do.` },
      ],
    },
  ],
};

export default en;
